-- Neovim Theme Configuration
-- Auto-generated by terminal theme system

local theme_file = os.getenv("HOME") .. "/.terminal-theme"
local theme = "dracula" -- default

-- Read theme preference
local f = io.open(theme_file, "r")
if f then
    local content = f:read("*all")
    f:close()
    -- Extract theme name from export TERMINAL_THEME='theme_name'
    local match = content:match("TERMINAL_THEME='([^']+)'")
    if match then
        theme = match
    end
end

-- Apply colorscheme
vim.schedule(function()
    local colorschemes = {
        dracula = "dracula",
        cyberpunk = "tokyonight",
        nord = "nord",
        gruvbox = "gruvbox"
    }
    
    local scheme = colorschemes[theme] or "default"
    
    -- Try to set the colorscheme, fail silently if not installed
    pcall(function()
        vim.cmd("colorscheme " .. scheme)
    end)
    
    -- Set background based on theme
    vim.opt.background = "dark"
    
    -- Theme-specific configurations
    if theme == "cyberpunk" and scheme == "tokyonight" then
        vim.g.tokyonight_style = "night"
        vim.g.tokyonight_transparent = false
        vim.g.tokyonight_terminal_colors = true
    elseif theme == "gruvbox" then
        vim.g.gruvbox_contrast_dark = "medium"
        vim.g.gruvbox_transparent_bg = 0
    end
end)